spring:
  application:
    name: fleet-management-server
  profiles:
    active: local
  datasource:
    username: ${SQL_USERNAME:admin}
    url: ${SQL_URI:jdbc:postgresql://localhost:5432/fleet_management}
    password: ${SQL_PASSWORD:admin}
  data:
    web:
      pageable:
        default-page-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
              - openid
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG