name: Run Server Tests
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - name: Test
        run: ./gradlew test --no-daemon
      - name: Generate JaCoCo Report
        run: ./gradlew jacocoTestReport --no-daemon
      - name: Check Generated Report
        run: cat build/reports/jacoco/test/jacocoTestReport.csv
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: server/build/reports/jacoco/test/jacocoTestReport.csv